POST http://localhost:8088/api/test HTTP/1.1
content-type: application/json

{
    "nomReservation": "Bastien Rossatto",
    "mailReservation": "bastien.rossatto@gmail.com",
    "telReservation": "0722446611",
    "dateReservation": "15/08/1988",
    "nbBilletReservation": "1"
}

###

GET http://localhost:8088/api/test

###

GET http://localhost:8088/api/test/yaQEqHAiDhMvBg9J

###

PATCH http://localhost:8088/api/test/yaQEqHAiDhMvBg9J HTTP/1.1
content-type: application/json

{
    "dateReservation": "22/11/2021",
    "telReservation": "0711223344"
}



###

DELETE http://localhost:8088/api/test/zrwMdnH5KVQ1zH8I